environment:
  global:
    # full path to Saxon jar
    SAXON_CP: '%TEMP%\xspec\saxon\saxon9he.jar'
    # Ant version used in oXygen
    ANT_VERSION: 1.9.8
    # full path to XML Resolver jar
    XML_RESOLVER_CP: '%TEMP%\xspec\xml-resolver\resolver.jar'
  matrix:
    # latest Saxon 9.8 version and full path to Jing jar
    - SAXON_VERSION: 9.8.0-7
      JING_CP: '%TEMP%\xspec\jing-trang\jing.jar'
    # latest Saxon 9.7 version
    - SAXON_VERSION: 9.7.0-21
      XMLCALABASH_VERSION: 1.1.21-97
      BASEX_VERSION: 8.6.4
    # Saxon version used in oXygen
    - SAXON_VERSION: 9.7.0-19

install:
- ps: >-
    # install Saxon

    curl.exe -fsSL --create-dirs -o "${env:SAXON_CP}" "http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/${env:SAXON_VERSION}/Saxon-HE-${env:SAXON_VERSION}.jar"


    # install XML Calabash

    if( -Not( Test-Path -Path env:\XMLCALABASH_VERSION ) ) {
        echo "XMLCalabash will not be installed as it uses a higher version of Saxon"
    }

    else {
        curl.exe -fsSL --create-dirs -o "${env:TEMP}\xspec\xmlcalabash\xmlcalabash.zip" "https://github.com/ndw/xmlcalabash1/releases/download/${env:XMLCALABASH_VERSION}/xmlcalabash-${env:XMLCALABASH_VERSION}.zip"
        7z x "${env:TEMP}\xspec\xmlcalabash\xmlcalabash.zip" -o"${env:TEMP}\xspec\xmlcalabash"
        ${env:XMLCALABASH_CP} = "${env:TEMP}\xspec\xmlcalabash\xmlcalabash-${env:XMLCALABASH_VERSION}\xmlcalabash-${env:XMLCALABASH_VERSION}.jar"
    }


    # install BaseX

    if( -Not( Test-Path -Path env:\BASEX_VERSION ) ) {
        echo "BaseX will not be installed as it requires to run XMLCalabash with a higher version of Saxon";
    }

    else {
        ${env:BASEX_CP} = "${env:TEMP}\xspec\basex\basex.jar"
        curl.exe -fsSL --create-dirs -o "${env:BASEX_CP}" "http://files.basex.org/maven/org/basex/basex/${env:BASEX_VERSION}/basex-${env:BASEX_VERSION}.jar"
    }


    # install Ant without installing JDK

    appveyor-retry choco install ant --ignore-dependencies --no-progress --version "${env:ANT_VERSION}"


    # install XML Resolver

    curl.exe -fsSL --create-dirs -o "${env:XML_RESOLVER_CP}" "http://central.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar"


    # install Jing

    if( -Not( Test-Path -Path env:\JING_CP ) ) {
        echo "Jing will not be installed"
    }

    else {
        curl.exe -fsSL --create-dirs -o "${env:JING_CP}" "http://central.maven.org/maven2/com/thaiopensource/jing/20091111/jing-20091111.jar"
    }
build: off
test_script:
- cmd: >-
    rem Print Java version

    java -version


    rem Print Ant version

    ant -version


    rem Print Saxon version

    java -cp "%SAXON_CP%" net.sf.saxon.Transform 2>&1 | find /i "saxon-"


    rem execute xspec.bat unit tests

    test\xspec-bat.cmd


    rem execute XSpec unit tests

    test\run-xspec-tests.cmd


    rem execute XSpec end-to-end tests

    test\end-to-end\run-e2e-tests.cmd
deploy: off
